/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  74
#define VERSION_USER   "lundman"
#define VERSION_HOST   "netbsd.interq.or.jp"
#define VERSION_DATE   "Wed Dec 28 12:08:03 2005"
#define VERSION_STRING "lundman@netbsd.interq.or.jp build 74 (Wed Dec 28 12:08:03 2005)"

/* Lundtastic services */
