/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  11
#define VERSION_USER   "lundman"
#define VERSION_HOST   "netbsd.interq.or.jp"
#define VERSION_DATE   "Fri Jul  7 17:06:26 2006"
#define VERSION_STRING "lundman@netbsd.interq.or.jp build 11 (Fri Jul  7 17:06:26 2006)"

/* Lundtastic services */
