/* This file is automagically generated by build. Do NOT edit. */

#define VERSION_BUILD  1
#define VERSION_USER   "lundman"
#define VERSION_HOST   "lundman"
#define VERSION_DATE   "Wed Apr 23 13:37:18 2003"
#define VERSION_STRING "lundman@lundman build 1 (Wed Apr 23 13:37:18 2003)"

/* Lundtastic services */
